// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Actor.proto

public final class ActorOuterClass {
  private ActorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ActorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Actor)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string surname = 2;</code>
     * @return Whether the surname field is set.
     */
    boolean hasSurname();
    /**
     * <code>required string surname = 2;</code>
     * @return The surname.
     */
    java.lang.String getSurname();
    /**
     * <code>required string surname = 2;</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    java.util.List<ActorOuterClass.Actor.Movie> 
        getMovieList();
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    ActorOuterClass.Actor.Movie getMovie(int index);
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    int getMovieCount();

    /**
     * <code>optional .Actor.Sex sex = 4;</code>
     * @return Whether the sex field is set.
     */
    boolean hasSex();
    /**
     * <code>optional .Actor.Sex sex = 4;</code>
     * @return The sex.
     */
    ActorOuterClass.Actor.Sex getSex();
  }
  /**
   * Protobuf type {@code Actor}
   */
  public  static final class Actor extends
      com.google.protobuf.GeneratedMessageLite<
          Actor, Actor.Builder> implements
      // @@protoc_insertion_point(message_implements:Actor)
      ActorOrBuilder {
    private Actor() {
      name_ = "";
      surname_ = "";
      movie_ = emptyProtobufList();
    }
    /**
     * Protobuf enum {@code Actor.Sex}
     */
    public enum Sex
        implements com.google.protobuf.Internal.EnumLite {
      /**
       * <code>MALE = 0;</code>
       */
      MALE(0),
      /**
       * <code>FEMALE = 1;</code>
       */
      FEMALE(1),
      ;

      /**
       * <code>MALE = 0;</code>
       */
      public static final int MALE_VALUE = 0;
      /**
       * <code>FEMALE = 1;</code>
       */
      public static final int FEMALE_VALUE = 1;


      @java.lang.Override
      public final int getNumber() {
        return value;
      }

      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return MALE;
          case 1: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              @java.lang.Override
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public static com.google.protobuf.Internal.EnumVerifier 
          internalGetVerifier() {
        return SexVerifier.INSTANCE;
      }

      private static final class SexVerifier implements 
           com.google.protobuf.Internal.EnumVerifier { 
              static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new SexVerifier();
              @java.lang.Override
              public boolean isInRange(int number) {
                return Sex.forNumber(number) != null;
              }
            };

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Actor.Sex)
    }

    public interface MovieOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Actor.Movie)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <code>required string title = 1;</code>
       * @return Whether the title field is set.
       */
      boolean hasTitle();
      /**
       * <code>required string title = 1;</code>
       * @return The title.
       */
      java.lang.String getTitle();
      /**
       * <code>required string title = 1;</code>
       * @return The bytes for title.
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <code>required int32 year = 2;</code>
       * @return Whether the year field is set.
       */
      boolean hasYear();
      /**
       * <code>required int32 year = 2;</code>
       * @return The year.
       */
      int getYear();
    }
    /**
     * Protobuf type {@code Actor.Movie}
     */
    public  static final class Movie extends
        com.google.protobuf.GeneratedMessageLite<
            Movie, Movie.Builder> implements
        // @@protoc_insertion_point(message_implements:Actor.Movie)
        MovieOrBuilder {
      private Movie() {
        title_ = "";
      }
      private int bitField0_;
      public static final int TITLE_FIELD_NUMBER = 1;
      private java.lang.String title_;
      /**
       * <code>required string title = 1;</code>
       * @return Whether the title field is set.
       */
      @java.lang.Override
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string title = 1;</code>
       * @return The title.
       */
      @java.lang.Override
      public java.lang.String getTitle() {
        return title_;
      }
      /**
       * <code>required string title = 1;</code>
       * @return The bytes for title.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(title_);
      }
      /**
       * <code>required string title = 1;</code>
       * @param value The title to set.
       */
      private void setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value;
      }
      /**
       * <code>required string title = 1;</code>
       */
      private void clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = getDefaultInstance().getTitle();
      }
      /**
       * <code>required string title = 1;</code>
       * @param value The bytes for title to set.
       */
      private void setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        title_ = value.toStringUtf8();
      }

      public static final int YEAR_FIELD_NUMBER = 2;
      private int year_;
      /**
       * <code>required int32 year = 2;</code>
       * @return Whether the year field is set.
       */
      @java.lang.Override
      public boolean hasYear() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 year = 2;</code>
       * @return The year.
       */
      @java.lang.Override
      public int getYear() {
        return year_;
      }
      /**
       * <code>required int32 year = 2;</code>
       * @param value The year to set.
       */
      private void setYear(int value) {
        bitField0_ |= 0x00000002;
        year_ = value;
      }
      /**
       * <code>required int32 year = 2;</code>
       */
      private void clearYear() {
        bitField0_ = (bitField0_ & ~0x00000002);
        year_ = 0;
      }

      public static ActorOuterClass.Actor.Movie parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ActorOuterClass.Actor.Movie parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static ActorOuterClass.Actor.Movie parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static ActorOuterClass.Actor.Movie parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return (Builder) DEFAULT_INSTANCE.createBuilder();
      }
      public static Builder newBuilder(ActorOuterClass.Actor.Movie prototype) {
        return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
      }

      /**
       * Protobuf type {@code Actor.Movie}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            ActorOuterClass.Actor.Movie, Builder> implements
          // @@protoc_insertion_point(builder_implements:Actor.Movie)
          ActorOuterClass.Actor.MovieOrBuilder {
        // Construct using ActorOuterClass.Actor.Movie.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <code>required string title = 1;</code>
         * @return Whether the title field is set.
         */
        @java.lang.Override
        public boolean hasTitle() {
          return instance.hasTitle();
        }
        /**
         * <code>required string title = 1;</code>
         * @return The title.
         */
        @java.lang.Override
        public java.lang.String getTitle() {
          return instance.getTitle();
        }
        /**
         * <code>required string title = 1;</code>
         * @return The bytes for title.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString
            getTitleBytes() {
          return instance.getTitleBytes();
        }
        /**
         * <code>required string title = 1;</code>
         * @param value The title to set.
         * @return This builder for chaining.
         */
        public Builder setTitle(
            java.lang.String value) {
          copyOnWrite();
          instance.setTitle(value);
          return this;
        }
        /**
         * <code>required string title = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearTitle() {
          copyOnWrite();
          instance.clearTitle();
          return this;
        }
        /**
         * <code>required string title = 1;</code>
         * @param value The bytes for title to set.
         * @return This builder for chaining.
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setTitleBytes(value);
          return this;
        }

        /**
         * <code>required int32 year = 2;</code>
         * @return Whether the year field is set.
         */
        @java.lang.Override
        public boolean hasYear() {
          return instance.hasYear();
        }
        /**
         * <code>required int32 year = 2;</code>
         * @return The year.
         */
        @java.lang.Override
        public int getYear() {
          return instance.getYear();
        }
        /**
         * <code>required int32 year = 2;</code>
         * @param value The year to set.
         * @return This builder for chaining.
         */
        public Builder setYear(int value) {
          copyOnWrite();
          instance.setYear(value);
          return this;
        }
        /**
         * <code>required int32 year = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearYear() {
          copyOnWrite();
          instance.clearYear();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Actor.Movie)
      }
      private byte memoizedIsInitialized = 2;
      @java.lang.Override
      @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
      protected final java.lang.Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          java.lang.Object arg0, java.lang.Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new ActorOuterClass.Actor.Movie();
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case BUILD_MESSAGE_INFO: {
              java.lang.Object[] objects = new java.lang.Object[] {
                "bitField0_",
                "title_",
                "year_",
              };
              java.lang.String info =
                  "\u0001\u0002\u0000\u0001\u0001\u0002\u0002\u0000\u0000\u0002\u0001\u0508\u0000\u0002" +
                  "\u0504\u0001";
              return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            com.google.protobuf.Parser<ActorOuterClass.Actor.Movie> parser = PARSER;
            if (parser == null) {
              synchronized (ActorOuterClass.Actor.Movie.class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<ActorOuterClass.Actor.Movie>(
                          DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return memoizedIsInitialized;
        }
        case SET_MEMOIZED_IS_INITIALIZED: {
          memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
          return null;
        }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:Actor.Movie)
      private static final ActorOuterClass.Actor.Movie DEFAULT_INSTANCE;
      static {
        Movie defaultInstance = new Movie();
        // New instances are implicitly immutable so no need to make
        // immutable.
        DEFAULT_INSTANCE = defaultInstance;
        com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          Movie.class, defaultInstance);
      }

      public static ActorOuterClass.Actor.Movie getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Movie> PARSER;

      public static com.google.protobuf.Parser<Movie> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.String name_;
    /**
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    @java.lang.Override
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return name_;
    }
    /**
     * <code>required string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The name to set.
     */
    private void setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value;
    }
    /**
     * <code>required string name = 1;</code>
     */
    private void clearName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>required string name = 1;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      name_ = value.toStringUtf8();
    }

    public static final int SURNAME_FIELD_NUMBER = 2;
    private java.lang.String surname_;
    /**
     * <code>required string surname = 2;</code>
     * @return Whether the surname field is set.
     */
    @java.lang.Override
    public boolean hasSurname() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string surname = 2;</code>
     * @return The surname.
     */
    @java.lang.Override
    public java.lang.String getSurname() {
      return surname_;
    }
    /**
     * <code>required string surname = 2;</code>
     * @return The bytes for surname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(surname_);
    }
    /**
     * <code>required string surname = 2;</code>
     * @param value The surname to set.
     */
    private void setSurname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      surname_ = value;
    }
    /**
     * <code>required string surname = 2;</code>
     */
    private void clearSurname() {
      bitField0_ = (bitField0_ & ~0x00000002);
      surname_ = getDefaultInstance().getSurname();
    }
    /**
     * <code>required string surname = 2;</code>
     * @param value The bytes for surname to set.
     */
    private void setSurnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      surname_ = value.toStringUtf8();
    }

    public static final int MOVIE_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.ProtobufList<ActorOuterClass.Actor.Movie> movie_;
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    @java.lang.Override
    public java.util.List<ActorOuterClass.Actor.Movie> getMovieList() {
      return movie_;
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    public java.util.List<? extends ActorOuterClass.Actor.MovieOrBuilder> 
        getMovieOrBuilderList() {
      return movie_;
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    @java.lang.Override
    public int getMovieCount() {
      return movie_.size();
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    @java.lang.Override
    public ActorOuterClass.Actor.Movie getMovie(int index) {
      return movie_.get(index);
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    public ActorOuterClass.Actor.MovieOrBuilder getMovieOrBuilder(
        int index) {
      return movie_.get(index);
    }
    private void ensureMovieIsMutable() {
      if (!movie_.isModifiable()) {
        movie_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(movie_);
       }
    }

    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void setMovie(
        int index, ActorOuterClass.Actor.Movie value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMovieIsMutable();
      movie_.set(index, value);
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void setMovie(
        int index, ActorOuterClass.Actor.Movie.Builder builderForValue) {
      ensureMovieIsMutable();
      movie_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void addMovie(ActorOuterClass.Actor.Movie value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMovieIsMutable();
      movie_.add(value);
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void addMovie(
        int index, ActorOuterClass.Actor.Movie value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureMovieIsMutable();
      movie_.add(index, value);
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void addMovie(
        ActorOuterClass.Actor.Movie.Builder builderForValue) {
      ensureMovieIsMutable();
      movie_.add(builderForValue.build());
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void addMovie(
        int index, ActorOuterClass.Actor.Movie.Builder builderForValue) {
      ensureMovieIsMutable();
      movie_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void addAllMovie(
        java.lang.Iterable<? extends ActorOuterClass.Actor.Movie> values) {
      ensureMovieIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, movie_);
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void clearMovie() {
      movie_ = emptyProtobufList();
    }
    /**
     * <code>repeated .Actor.Movie movie = 3;</code>
     */
    private void removeMovie(int index) {
      ensureMovieIsMutable();
      movie_.remove(index);
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>optional .Actor.Sex sex = 4;</code>
     * @return Whether the sex field is set.
     */
    @java.lang.Override
    public boolean hasSex() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional .Actor.Sex sex = 4;</code>
     * @return The sex.
     */
    @java.lang.Override
    public ActorOuterClass.Actor.Sex getSex() {
      ActorOuterClass.Actor.Sex result = ActorOuterClass.Actor.Sex.forNumber(sex_);
      return result == null ? ActorOuterClass.Actor.Sex.MALE : result;
    }
    /**
     * <code>optional .Actor.Sex sex = 4;</code>
     * @param value The sex to set.
     */
    private void setSex(ActorOuterClass.Actor.Sex value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000004;
      sex_ = value.getNumber();
    }
    /**
     * <code>optional .Actor.Sex sex = 4;</code>
     */
    private void clearSex() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sex_ = 0;
    }

    public static ActorOuterClass.Actor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ActorOuterClass.Actor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ActorOuterClass.Actor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ActorOuterClass.Actor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ActorOuterClass.Actor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static ActorOuterClass.Actor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static ActorOuterClass.Actor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ActorOuterClass.Actor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ActorOuterClass.Actor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static ActorOuterClass.Actor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static ActorOuterClass.Actor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static ActorOuterClass.Actor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(ActorOuterClass.Actor prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Actor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          ActorOuterClass.Actor, Builder> implements
        // @@protoc_insertion_point(builder_implements:Actor)
        ActorOuterClass.ActorOrBuilder {
      // Construct using ActorOuterClass.Actor.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string name = 1;</code>
       * @return Whether the name field is set.
       */
      @java.lang.Override
      public boolean hasName() {
        return instance.hasName();
      }
      /**
       * <code>required string name = 1;</code>
       * @return The name.
       */
      @java.lang.Override
      public java.lang.String getName() {
        return instance.getName();
      }
      /**
       * <code>required string name = 1;</code>
       * @return The bytes for name.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>required string surname = 2;</code>
       * @return Whether the surname field is set.
       */
      @java.lang.Override
      public boolean hasSurname() {
        return instance.hasSurname();
      }
      /**
       * <code>required string surname = 2;</code>
       * @return The surname.
       */
      @java.lang.Override
      public java.lang.String getSurname() {
        return instance.getSurname();
      }
      /**
       * <code>required string surname = 2;</code>
       * @return The bytes for surname.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        return instance.getSurnameBytes();
      }
      /**
       * <code>required string surname = 2;</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          java.lang.String value) {
        copyOnWrite();
        instance.setSurname(value);
        return this;
      }
      /**
       * <code>required string surname = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        copyOnWrite();
        instance.clearSurname();
        return this;
      }
      /**
       * <code>required string surname = 2;</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSurnameBytes(value);
        return this;
      }

      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      @java.lang.Override
      public java.util.List<ActorOuterClass.Actor.Movie> getMovieList() {
        return java.util.Collections.unmodifiableList(
            instance.getMovieList());
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      @java.lang.Override
      public int getMovieCount() {
        return instance.getMovieCount();
      }/**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      @java.lang.Override
      public ActorOuterClass.Actor.Movie getMovie(int index) {
        return instance.getMovie(index);
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder setMovie(
          int index, ActorOuterClass.Actor.Movie value) {
        copyOnWrite();
        instance.setMovie(index, value);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder setMovie(
          int index, ActorOuterClass.Actor.Movie.Builder builderForValue) {
        copyOnWrite();
        instance.setMovie(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder addMovie(ActorOuterClass.Actor.Movie value) {
        copyOnWrite();
        instance.addMovie(value);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder addMovie(
          int index, ActorOuterClass.Actor.Movie value) {
        copyOnWrite();
        instance.addMovie(index, value);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder addMovie(
          ActorOuterClass.Actor.Movie.Builder builderForValue) {
        copyOnWrite();
        instance.addMovie(builderForValue);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder addMovie(
          int index, ActorOuterClass.Actor.Movie.Builder builderForValue) {
        copyOnWrite();
        instance.addMovie(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder addAllMovie(
          java.lang.Iterable<? extends ActorOuterClass.Actor.Movie> values) {
        copyOnWrite();
        instance.addAllMovie(values);
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder clearMovie() {
        copyOnWrite();
        instance.clearMovie();
        return this;
      }
      /**
       * <code>repeated .Actor.Movie movie = 3;</code>
       */
      public Builder removeMovie(int index) {
        copyOnWrite();
        instance.removeMovie(index);
        return this;
      }

      /**
       * <code>optional .Actor.Sex sex = 4;</code>
       * @return Whether the sex field is set.
       */
      @java.lang.Override
      public boolean hasSex() {
        return instance.hasSex();
      }
      /**
       * <code>optional .Actor.Sex sex = 4;</code>
       * @return The sex.
       */
      @java.lang.Override
      public ActorOuterClass.Actor.Sex getSex() {
        return instance.getSex();
      }
      /**
       * <code>optional .Actor.Sex sex = 4;</code>
       * @param value The enum numeric value on the wire for sex to set.
       * @return This builder for chaining.
       */
      public Builder setSex(ActorOuterClass.Actor.Sex value) {
        copyOnWrite();
        instance.setSex(value);
        return this;
      }
      /**
       * <code>optional .Actor.Sex sex = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSex() {
        copyOnWrite();
        instance.clearSex();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Actor)
    }
    private byte memoizedIsInitialized = 2;
    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new ActorOuterClass.Actor();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "bitField0_",
              "name_",
              "surname_",
              "movie_",
              ActorOuterClass.Actor.Movie.class,
              "sex_",
              ActorOuterClass.Actor.Sex.internalGetVerifier(),
            };
            java.lang.String info =
                "\u0001\u0004\u0000\u0001\u0001\u0004\u0004\u0000\u0001\u0003\u0001\u0508\u0000\u0002" +
                "\u0508\u0001\u0003\u041b\u0004\f\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<ActorOuterClass.Actor> parser = PARSER;
          if (parser == null) {
            synchronized (ActorOuterClass.Actor.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<ActorOuterClass.Actor>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return memoizedIsInitialized;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Actor)
    private static final ActorOuterClass.Actor DEFAULT_INSTANCE;
    static {
      Actor defaultInstance = new Actor();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Actor.class, defaultInstance);
    }

    public static ActorOuterClass.Actor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Actor> PARSER;

    public static com.google.protobuf.Parser<Actor> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
